basic:
    name: 'https://www.adpkdquestions.com'
    environments:
        production: 'https://www.adpkdquestions.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1080
        - 1440
    pages:
        - /
        - /es
        - /adpkd-background
        - /es/adpkd-descripcion-general
        - /adpkd-diagnosis
        - /es/adpkd-diagnostico
        - /adpkd-kidney-size
        - /es/adpkd-informacion-de-contexto
        - /risk-of-adpkd-progression
        - /es/riesgo-de-adpkd-progresion
        - /assessing-kidney-size
        - /es/evaluar-el-tamano-del-rinon
        - /living-with-adpkd
        - /es/vivir-con-adpkd
        - /find-a-doctor
        - /es/encontrar-un-medico
        - /downloadable-resources
        - /es/tarjetas-de-conversacion
        - /foundations-advocacy-groups
        - /es/fundaciones-grupos-de-defensa
        - /sign-up
        - /es/registrarse
        - /sitemap
        - /es/mapa-del-sitio
        - /sms-terms-conditions
        - /es/terminos-y-condiciones-de-los-sms
        - /404
        - /es/404
        - /Receiving-an-ADPKD-diagnosis
        - /ADPKD-through-their-eyes
        - /what-to-know
        - /es/what-to-know
        - /helpful
        - /es/helpful
        - /diagnosed-no
        - /es/diagnosed-no
        - /diagnosed-yes
        - /es/diagnosed-yes
        - /page
        - /es/page
        - /not-so-helpful
        - /es/not-so-helpful
        - /interactive-kidney
        - /community-voices
        - /es/historias-de-pacientes
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: video
    remove: '#videoBackground'
    delay: 15
    scroll: false
    headers:
        - { value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36', header: User-Agent }
    cookies: cookie-agreed=1
    custom_js: "document.querySelector(\"#onetrust-accept-btn-handler\").click()\njQuery(\"#notification-popup .analytics--o-exit-close\").click();\n\n\nconst video = document.querySelector('video');\nif (video) {\n  const canvas = document.createElement('canvas');\n  canvas.width = video.videoWidth;\n  canvas.height = video.videoHeight;\n\n  const ctx = canvas.getContext('2d');\n  ctx.drawImage(video, 0, 0, canvas.width, canvas.height);\n\n  const img = document.createElement('img');\n  img.src = canvas.toDataURL();\n  img.style.width = video.style.width || '100%';\n  img.style.height = video.style.height || '100%';\n\n  video.parentNode.replaceChild(img, video);\n  console.log('? Видео заменено на замороженный кадр.');\n}\n"
    custom_css: ".container.paragraph {\n\tposition: static !important;\n}"
    mock_content: {  }
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
