basic:
    name: 'https://www.adpkdquestions.com'
    environments:
        production: 'https://www.adpkdquestions.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1080
        - 1440
    pages:
        - /
        - /Receiving-an-ADPKD-diagnosis
        - /ADPKD-through-their-eyes
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: '#videoBackground'
    delay: 60
    scroll: false
    headers:
        - { value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36', header: User-Agent }
    cookies: ''
    custom_js: "document.querySelector(\"#onetrust-accept-btn-handler\").click()\njQuery(\"#notification-popup .analytics--o-exit-close\").click();\n\nconst canvas = document.createElement('canvas');\n      canvas.width = video.videoWidth || video.clientWidth;\n      canvas.height = video.videoHeight || video.clientHeight;\n      const ctx = canvas.getContext('2d');\n      ctx.drawImage(video, 0, 0, canvas.width, canvas.height);\n\n      // Create image from canvas\n      const img = document.createElement('img');\n      img.src = canvas.toDataURL('image/png');\n      img.style = video.style.cssText;\n      img.width = video.clientWidth;\n      img.height = video.clientHeight;\n\n      // Replace video with static image\n      video.parentNode.replaceChild(img, video);"
    custom_css: ".container.paragraph {\n\tposition: static !important;\n}"
    mock_content: {  }
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: true
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
