basic:
    name: 'https://www.adpkdquestions.com'
    environments:
        production: 'https://www.adpkdquestions.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1080
        - 1440
    pages:
        - /
        - /Receiving-an-ADPKD-diagnosis
        - /ADPKD-through-their-eyes
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: '#videoBackground'
    delay: 60
    scroll: false
    headers:
        - { value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36', header: User-Agent }
    cookies: ''
    custom_js: "document.querySelector(\"#onetrust-accept-btn-handler\").click()\njQuery(\"#notification-popup .analytics--o-exit-close\").click();\n  const videos = document.querySelectorAll('video');\n  videos.forEach(video => {\n    try {\n      const rect = video.getBoundingClientRect();\n\n      const canvas = document.createElement('canvas');\n      canvas.width = rect.width;\n      canvas.height = rect.height;\n\n      const ctx = canvas.getContext('2d');\n      ctx.drawImage(video, 0, 0, rect.width, rect.height);\n\n      const img = document.createElement('img');\n      img.src = canvas.toDataURL('image/png');\n      img.style.position = 'absolute';\n      img.style.top = rect.top + window.scrollY + 'px';\n      img.style.left = rect.left + window.scrollX + 'px';\n      img.style.width = rect.width + 'px';\n      img.style.height = rect.height + 'px';\n      img.style.zIndex = '999999'; // max priority\n      img.style.pointerEvents = 'none';\n\n      document.body.appendChild(img);\n      video.remove(); // remove video from DOM entirely\n    } catch (e) {\n      console.error('Video freeze failed:', e);\n    }\n  });"
    custom_css: ".container.paragraph {\n\tposition: static !important;\n}"
    mock_content: {  }
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: true
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
